server:
  port: 8080

spring:
  application:
    name: vector-pgvector

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yingzi_db
    username: yingzi_user
    password: yingzi_password