server:
  port: 8080
spring:
  application:
    name: observe-langfuse
  profiles:
    # LangFuse可观测配置
    include: observability
  ai:
    openai:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

    alibaba:
      graph:
        observation:
          enabled: true
