server:
  port: 8080

spring:
  application:
    name: advisor-memory-neo4j

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: yingzi_password